### ISSUE TITLE
Only image could be sent to WhatsApp

### ISSUE THREAD

**Issue by s1u** [mvarie/MMMWhatsAppActivity#1]
I have an `activityItems` that is `NSArray  * activityItems = @[sharedText,sharedIcon,sharedUrl];`, but found only the icon is sent to WhatsApp. url and text are not got. Why?

Could you improve it so as to send text/image/url simultaneously to WhatsApp?

Thanks!

**Comment by mvarie** [comment]
WhatsApp does not support simultaneously receiving image and text. I wish they did.
